- name: variables to print
 hosts: web
 vars: #These are play level variables, all tasks in this play can access to this
  COURSE: "Devops with AWS"
  DURATION: "120HRS"
  TRAINER: "Sivakumar Reddy M"
 tasks:
 - name: print the information
   ansible.builtin.debug:
    msg: "I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"

  - name: print the information again
    vars: #task level variables override play level
    COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"

    - name: print the information again
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
