- name: variables from file
 hosts: web
 vars_file:
 - vars.yaml
 tasks: 
 - name: print the course information
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"