- name: variable from inventory file
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}
      