- name: check a number is less than 10 or not
  hosts: localhost
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false # not confidential
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: my_number < 10 # conditional expression
  
  - name: print this if grater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is greater than or equal to 10"
    when: my_number >= 10 