- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'ngnix', state: 'absent' }
    - { name: 'postfix', state: 'adesnt' }
    - { name: 'httpd', state: 'present' }