- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
  
  - name: convert to uppercase
    vars:
      greeting: "Hello Teja"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "

  - name: convert to lowercase
    vars:
      greeting: "Hello Teja"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }} "
  
  - name: get the unique values
    vars:
     numbers: [1,2,3,45,4,3,2,]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max
    vars:
     numbers: [1,2,3,45,4,3,2,]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: "120"
        trainer: "shivakumar reddy"
    ansible.builtin.debug:
      msg: "{{ course | dict2items}}"

  - name: convert list to map
    vars:
      course:
        - { "key": "name", "value": "Devops with AWS" }
        - {"key": "duration", "value": "120" }
        - {"key": "trainer", "value": "shivakumar reddy"}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"
    
  - name: check the IP as ipv4 or not
    vars:
      myip: "356.168.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"
