- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0568ffe35f689a784
    sg_id: sg-087343d4de742d430
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: tejadevops.site
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: " {{ ec2_instances }} "
  
#private IP R53
  - name: create route53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.tejadevops.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create route53 public records for froentend  #public routes is only with froentend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #tejadevops.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "froentend" #when keyword should not have {{}}